import {
  db,
  worldsTable,
  areasTable,
  categoriesTable,
  serviceTemplatesTable,
} from "@workspace/db";
import { asc } from "drizzle-orm";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Dumps the classification reference data (worlds, areas, categories,
 * service templates) from the CURRENT dev database into a generated TS module
 * inside the api-server, where `ensureClassificationCatalog()` upserts it at
 * boot. This is how production gets the Branchen catalog: the seed script
 * (scripts/src/seed.ts) only ever runs against dev, so the snapshot is the
 * bridge that ships the catalog with the server bundle.
 *
 * Volatile columns are stripped: serial `id`s (rows are keyed by slug / string
 * id) and `providerCount` (recomputed from the providers table at boot).
 */
export async function writeClassificationSnapshot(): Promise<string> {
  const worlds = await db
    .select()
    .from(worldsTable)
    .orderBy(asc(worldsTable.displayOrder), asc(worldsTable.id));
  const areas = await db
    .select()
    .from(areasTable)
    .orderBy(asc(areasTable.worldId), asc(areasTable.displayOrder), asc(areasTable.id));
  const rawCategories = await db
    .select()
    .from(categoriesTable)
    .orderBy(asc(categoriesTable.slug));
  const rawTemplates = await db
    .select()
    .from(serviceTemplatesTable)
    .orderBy(asc(serviceTemplatesTable.sortOrder), asc(serviceTemplatesTable.id));

  if (worlds.length === 0 || rawCategories.length === 0) {
    throw new Error(
      "Refusing to write an empty classification snapshot — seed the dev DB first (pnpm --filter @workspace/scripts run seed).",
    );
  }

  const categories = rawCategories.map(({ id: _id, providerCount: _pc, ...rest }) => rest);
  const serviceTemplates = rawTemplates.map(({ id: _id, ...rest }) => rest);

  const snapshot = { worlds, areas, categories, serviceTemplates };
  const body =
    "// AUTO-GENERATED by scripts/src/snapshotClassification.ts — DO NOT EDIT BY HAND.\n" +
    "// Regenerate after taxonomy changes in the dev DB:\n" +
    "//   pnpm --filter @workspace/scripts run snapshot:classification\n" +
    "// (scripts/src/seed.ts regenerates it automatically at the end of a seed run.)\n" +
    `export const CLASSIFICATION_SNAPSHOT = ${JSON.stringify(snapshot, null, 2)};\n`;
  const outPath = resolve(
    __dirname,
    "../../artifacts/api-server/src/seed-data/classificationSnapshot.ts",
  );
  writeFileSync(outPath, body);
  console.log(
    `Snapshot written: ${worlds.length} worlds, ${areas.length} areas, ` +
      `${categories.length} categories, ${serviceTemplates.length} service templates → ${outPath}`,
  );
  return outPath;
}

const invokedDirectly =
  process.argv[1] != null &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  writeClassificationSnapshot()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
