import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import classificationRouter from "./classification";
import providersRouter from "./providers";
import servicesRouter from "./services";
import serviceTemplatesRouter from "./serviceTemplates";
import availabilityRouter from "./availability";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import aiRouter from "./ai";
import dashboardRouter from "./dashboard";
import billingRouter from "./billing";
import connectRouter from "./connect";
import calendarRouter from "./calendar";
import storageRouter from "./storage";
import assessmentsRouter from "./assessments";
import invoicesRouter from "./invoices";
import adminRouter from "./admin";
import energieRouter from "./energie";
import gebaeudecheckRouter from "./gebaeudecheck";
import foerderschieneRouter from "./foerderschiene";
import foerderpilotRouter from "./foerderpilot";
import foerderpilotVorgangRouter from "./foerderpilotVorgang";
import financeAffiliateRouter from "./financeAffiliate";
import immobilienKundeRouter from "./immobilienKunde";
import immobilienPortfolioRouter from "./immobilienPortfolio";
import verwalteteKundenRouter from "./verwalteteKunden";
import customerProfileRouter from "./customerProfile";
import offersRouter from "./offers";
import accountRouter from "./account";
import requestsRouter from "./requests";
import providerRequestsRouter from "./providerRequests";

const router: IRouter = Router();

router.use(healthRouter);
router.use(categoriesRouter);
router.use(classificationRouter);
router.use(billingRouter);
router.use(connectRouter);
router.use(calendarRouter);
router.use(providersRouter);
router.use(serviceTemplatesRouter);
router.use(servicesRouter);
router.use(availabilityRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(aiRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(assessmentsRouter);
router.use(invoicesRouter);
router.use(adminRouter);
router.use(energieRouter);
router.use(gebaeudecheckRouter);
router.use(foerderschieneRouter);
router.use(foerderpilotRouter);
router.use(foerderpilotVorgangRouter);
router.use(financeAffiliateRouter);
router.use(immobilienKundeRouter);
router.use(immobilienPortfolioRouter);
router.use(verwalteteKundenRouter);
router.use(customerProfileRouter);
router.use(offersRouter);
router.use(accountRouter);
router.use(requestsRouter);
router.use(providerRequestsRouter);

export default router;
